### ISSUE TITLE
Both players...

### ISSUE THREAD

**Issue by schreiby** [ayahc1093/BlackjackSingleDevice#4]
Both players are dealt the same cards, AND can win without it being called a DRAW.

![screenshot_2015-07-20-16-33-43](https://cloud.githubusercontent.com/assets/11258395/8786752/0a3895d2-2efe-11e5-8523-fdbf0a3fefd5.png)

**Comment by ayahc1093** [comment]
Ouch

**Comment by schreiby** [comment]
All players with same cards and winning!!! Must debug!
![screenshot_2015-07-20-17-15-44](https://cloud.githubusercontent.com/assets/11258395/8787620/1fdd738a-2f03-11e5-8b74-0f53f0780876.png)

**Comment by schreiby** [comment]
Fixed by ayahc1093 in commit 4b5b80d1defd7ff053040365ec03d389d0a245e5

**Comment by schreiby** [comment]
Fixed by ayahc1093, see commit 4b5b80d1defd7ff053040365ec03d389d0a245e5
